//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionario_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Operacion
    {
        public int ID_Operacion { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd.MM.yy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fecha { get; set; }
        [RegularExpression(@"(?:compra|venta)")]
        public string tipo { get; set; }
        public Nullable<int> ID_empleado { get; set; }
        public Nullable<int> ID_cliente { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> ID_vehiculo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
