//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionario_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehiculos
    {
        public Vehiculos()
        {
            this.Operacion = new HashSet<Operacion>();
        }
    
        public int ID_Vehiculo { get; set; }
        public string marca { get; set; }
        public Nullable<int> numeroPuertas { get; set; }
        public string color { get; set; }
        public Nullable<float> kilometros { get; set; }
        [RegularExpression(@"(?:utilitario|coupe|familiar|SUV|industrial)")]
        public string tipoVehiculo { get; set; }
        public Nullable<int> garantia { get; set; }
        public Nullable<bool> enStock { get; set; }
        public Nullable<bool> fotografia { get; set; }
        public string modelo { get; set; }
    
        public virtual ICollection<Operacion> Operacion { get; set; }
    }
}
